development:
  adapter: postgresql
  encoding: unicode
  database: kart_development
  pool: 5
  username: kart
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: kart_test
  pool: 5
  username: kart
  password: password
